### ISSUE TITLE
SQL error or missing database (no such table: cas)

### ISSUE THREAD

**Issue by pbharrin** [oaqa/helloqa#12]
Running this project as specified in the README fails for me giving the following error: 
SQL error or missing database (no such table: cas)
I have looked into the sqlite db: oaqa-eval.db3 and there is in fact no table named cas, there is a cas_str table.  This happened on both the master and prototype branches.  

The output and stack trace are below:
[1]  Execution failed for option: SimpleKeytermExtractor[persistence-provider:inherit: ecd.default-log-persistence-provider] after 0s
Aug 22, 2013 10:38:27 AM org.apache.uima.util.CasPool releaseCas
WARNING: The system tried to return a common analysis structure to the pool from which it was not checked out.
Aug 22, 2013 10:38:27 AM org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl callAnalysisComponentNext(523)
SEVERE: Exception occurred
org.apache.uima.analysis_engine.AnalysisEngineProcessException
    at edu.cmu.lti.oaqa.ecd.phase.BasePhase.next(BasePhase.java:185)
    at edu.cmu.lti.oaqa.ecd.phase.BasePhase.next(BasePhase.java:73)
    at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentNext(PrimitiveAnalysisEngine_impl.java:500)
    at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl$AnalysisComponentCasIterator.next(PrimitiveAnalysisEngine_impl.java:613)
    at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:569)
    at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:409)
    at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:342)
    at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:267)
    at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:267)
    at edu.cmu.lti.oaqa.ecd.driver.SimplePipelineRev803.runPipeline(SimplePipelineRev803.java:244)
    at edu.cmu.lti.oaqa.ecd.driver.SimplePipelineRev803.runPipeline(SimplePipelineRev803.java:154)
    at edu.cmu.lti.oaqa.ecd.driver.ECDDriver.run(ECDDriver.java:66)
    at edu.cmu.lti.oaqa.ecd.driver.ECDDriver.main(ECDDriver.java:96)
Caused by: org.apache.uima.analysis_engine.AnalysisEngineProcessException
    at edu.cmu.lti.oaqa.ecd.phase.BasePhase.next(BasePhase.java:180)
    ... 12 more
Caused by: org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL []; SQL state [null]; error code [0]; [SQLITE_ERROR] SQL error or missing database (no such table: cas); nested exception is java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: cas)
    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:83)
    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
    at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:602)
    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:811)
    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:833)
    at edu.cmu.lti.oaqa.cse.driver.phase.impl.JdbcPhasePersistenceProvider.insertExecutionTrace(JdbcPhasePersistenceProvider.java:29)
    at edu.cmu.lti.oaqa.ecd.phase.BasePhase.insertExecutionTrace(BasePhase.java:278)
    at edu.cmu.lti.oaqa.ecd.phase.BasePhase.process(BasePhase.java:195)
    at edu.cmu.lti.oaqa.ecd.phase.BasePhase.next(BasePhase.java:175)
    ... 12 more

**Comment by bpodgursky** [comment]
Ran into the same problem.  Seems like something to messed up in the most recent commit to that file (https://github.com/oaqa/helloqa/commit/3fffe47e2448132bafff71dbd154d9f1be58afee#diff-0a56198bc7a6c442f43278938ded3409).  I jumped back a revision to get the schema for table "cas".  I had to recreate it manually by jumping into sqlite console ("sqlite3 data/oaqa-eval.db3") and creating the table:

CREATE TABLE cas(id INT, experiment CHAR, dataset CHAR, date TIMESTAMP, hostname VARCHAR, optionId VARCHAR, phase INT, phaseUid VARCHAR, predecesorId INT,question TEXT, sequenceId INT, startTime BIGINT, trace VARCHAR, answer TEXT, answerPattern TEXT, endTime BIGINT, isCorrect BIT, status VARCHAR, xcas LONGBLOB, traceHash CHAR);

checked the updated db file into my fork, among a ton of other dependencies I had to add to get an example running (https://github.com/bpodgursky/helloqa).

**Comment by noyessie** [comment]
Please, What is the utility of this database ?
