### ISSUE TITLE
NoClassDefFoundError: org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by KnowledgeGarden** [oaqa/helloqa#13]
NoClassDefFoundError: org/slf4j/LoggerFactory
    at org.apache.solr.core.SolrResourceLoader.<clinit>(SolrResourceLoader.java:66)

Booted in a fresh Kepler Eclipse. First boot got that error message.
Then tried a mvn clean install and re-run. Nothing changed.

**Comment by KnowledgeGarden** [comment]
I managed to move that exception to this one:
 java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such table: cas)
by creating a lib/ directory in the eclipse project and filling it with missing jars. That failure follows this one:

SEVERE: java.lang.NoClassDefFoundError: org/apache/commons/httpclient/HttpConnectionManager
    at org.apache.solr.handler.component.SearchHandler.<init>(SearchHandler.java:52)

even though I installed the HTTPClient jars from a Solr 3.6 war file., along with the full Lucene 3.6 collection, and various other jar files.

**Comment by KnowledgeGarden** [comment]
Replacing HTTPClient 4 jars with HTTPClient 3.0.1 got rid of the missing HttpConnectionManager (it's not clear how Solr will run without the 4.0 clients), but the missing database issue remains.
