### ISSUE TITLE
Beginner questions, java.lang.NoClassDefFoundError: javax/servlet/ServletRequest

### ISSUE THREAD

**Issue by k0105** [oaqa/helloqa#15]
Hi,

I'm trying to get started with OAQA. My goal for now is a project that can answer basic questions as a stepping stone for more involved work (general knowledge would be preferred). Hence, I tried to compile HelloQA following the instructions (downloaded Gutenberg, extracted files, opened project in Eclipse 4.5.1, ran test.launch), but it throws java.lang.NoClassDefFoundErrors. I have been able to solve some by adding `<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-log4j12</artifactId>
    <version>1.7.13</version>
</dependency>
<dependency>  
      <groupId>org.apache.lucene</groupId>  
      <artifactId>lucene-core</artifactId>  
      <version>3.6.0</version>  
</dependency>
<dependency>
    <groupId>commons-fileupload</groupId>
    <artifactId>commons-fileupload</artifactId>
    <version>1.3</version>
</dependency>` to pom.xml

But I now get `Phase: 2|retrieval-strategist>
Exception in thread "main" java.lang.NoClassDefFoundError: javax/servlet/ServletRequest`

Since I'm completely inexperienced with this pipeline: What can I do now? Did you make any assumptions? Right now I have set up neither UIMA, Indri, CSE nor any other OAQA projects. Was I supposed to?

Thanks in advance.

Best wishes,
Joe

**Comment by k0105** [comment]
OK, let me append the full output:
`log4j:WARN No appenders could be found for logger (org.springframework.core.io.support.PathMatchingResourcePatternResolver).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
openqa.collection.filename system property not specified, using 'file' parameter from configuration file
Reading file: /input/small.txt from the classpath
Phase: 2|retrieval-strategist>
Exception in thread "main" java.lang.NoClassDefFoundError: javax/servlet/ServletRequest
    at org.apache.solr.servlet.SolrRequestParsers.<init>(SolrRequestParsers.java:95)
    at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.<init>(EmbeddedSolrServer.java:91)
    at edu.cmu.lti.oaqa.core.provider.solr.SolrWrapper.createEmbeddedSolrServer(SolrWrapper.java:80)
    at edu.cmu.lti.oaqa.core.provider.solr.SolrWrapper.<init>(SolrWrapper.java:45)
    at edu.cmu.lti.oaqa.openqa.hello.retrieval.SimpleSolrRetrievalStrategist.initialize(SimpleSolrRetrievalStrategist.java:58)
    at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:250)
    at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initialize(PrimitiveAnalysisEngine_impl.java:156)
    at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
    at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
    at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:269)
    at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:314)
    at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:425)
    at org.uimafit.factory.AnalysisEngineFactory.createAggregate(AnalysisEngineFactory.java:424)
    at edu.cmu.lti.oaqa.ecd.phase.BasePhase.loadOptions(BasePhase.java:326)
    at edu.cmu.lti.oaqa.ecd.phase.BasePhase.initialize(BasePhase.java:119)
    at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:250)
    at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initialize(PrimitiveAnalysisEngine_impl.java:156)
    at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
    at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
    at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:269)
    at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:387)
    at org.apache.uima.analysis_engine.asb.impl.ASB_impl.setup(ASB_impl.java:254)
    at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initASB(AggregateAnalysisEngine_impl.java:431)
    at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initializeAggregateAnalysisEngine(AggregateAnalysisEngine_impl.java:375)
    at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initialize(AggregateAnalysisEngine_impl.java:185)
    at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
    at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
    at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:269)
    at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:314)
    at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:425)
    at org.uimafit.factory.AnalysisEngineFactory.createAggregate(AnalysisEngineFactory.java:424)
    at edu.cmu.lti.oaqa.ecd.BaseExperimentBuilder.buildPipeline(BaseExperimentBuilder.java:166)
    at edu.cmu.lti.oaqa.ecd.BaseExperimentBuilder.buildPipeline(BaseExperimentBuilder.java:143)
    at edu.cmu.lti.oaqa.ecd.driver.ECDDriver.run(ECDDriver.java:63)
    at edu.cmu.lti.oaqa.ecd.driver.ECDDriver.main(ECDDriver.java:96)
Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletRequest
    at java.net.URLClassLoader$1.run(URLClassLoader.java:359)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 35 more`

And let me take a wild guess as well: This is somehow caused by the Solr server, right? Are you trying to launch an embedded Solr server? Can I somehow run it standalone?

I'd really appreciate some help here.
